test_xml_reader: test_xml_reader_argument_parsing.bats test_xml_reader_output.bats
	bats ./test_xml_reader_argument_parsing.bats
	bats ./test_xml_reader_output.bats

test_sort_performance: test_sort_performance.bats
	bats ./test_sort_performance.bats

check: test_xml_reader
